package com.example.short_link.user.application;

import com.example.short_link.link.domain.ClickEventRepository;
import com.example.short_link.link.domain.LinkEntity;
import com.example.short_link.link.domain.LinkRepository;
import com.example.short_link.user.domain.UserRepository;
import io.micrometer.core.instrument.MeterRegistry;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * GDPR Article 17 / PIPA right-to-erasure: hard-deletes the user, all owned links, and all click
 * events generated by those links. Refresh tokens are wiped from Redis. Anonymous links remain
 * untouched.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class UserDeletionService {

  private final UserRepository userRepository;
  private final LinkRepository linkRepository;
  private final ClickEventRepository clickEventRepository;
  private final RefreshTokenStore refreshTokenStore;
  private final MeterRegistry meterRegistry;

  @Transactional
  public void deleteAccount(Long userId) {
    if (userId == null || !userRepository.existsById(userId)) {
      throw new UserNotFoundException();
    }

    List<LinkEntity> links = linkRepository.findAllByUserIdOrderByCreatedAtDesc(userId);
    if (!links.isEmpty()) {
      List<Long> linkIds = links.stream().map(LinkEntity::getId).toList();
      int deletedClicks = clickEventRepository.deleteByLinkIds(linkIds);
      log.info("user {} deletion: {} click events removed", userId, deletedClicks);
    }

    int deletedLinks = linkRepository.deleteByUserId(userId);
    log.info("user {} deletion: {} links removed", userId, deletedLinks);

    refreshTokenStore.deleteAllForUser(userId);
    userRepository.deleteById(userId);

    meterRegistry
        .counter("user.deleted", "links_removed", String.valueOf(deletedLinks))
        .increment();
  }
}
