package com.example.short_link.profile.application;

import java.util.Set;

public final class ReservedUsernames {

  public static final Set<String> ALL =
      Set.of(
          "abuse",
          "actor",
          "admin",
          "api",
          "app",
          "assets",
          "auth",
          "beta",
          "billing",
          "blog",
          "cdn",
          "contact",
          "dashboard",
          "data",
          "dev",
          "docs",
          "explore",
          "followers",
          "ftp",
          "help",
          "home",
          "hostmaster",
          "images",
          "img",
          "inbox",
          "info",
          "instance",
          "kurl",
          "links",
          "login",
          "logout",
          "mail",
          "me",
          "media",
          "moderator",
          "nodeinfo",
          "noreply",
          "oauth2",
          "official",
          "origin",
          "outbox",
          "postmaster",
          "pricing",
          "privacy",
          "public",
          "relay",
          "report",
          "robots",
          "root",
          "security",
          "settings",
          "signup",
          "sitemap",
          "smtp",
          "staff",
          "staging",
          "static",
          "stats",
          "status",
          "support",
          "swagger",
          "team",
          "terms",
          "tos",
          "u",
          "user",
          "users",
          "v1",
          "webfinger",
          "webmaster",
          "www");

  private ReservedUsernames() {}
}
